# Generated by Django 5.2.1 on 2025-05-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_consumerprofile_balance_service_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
